/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.plaf.TabbedPaneUI;

/**
 *
 * @author camsl
 */
public class testONglet extends javax.swing.JPanel {

     private final JPanel central;
    /**
     * Creates new form testONglet
     */
    public testONglet() {
        initComponents();
        central = new JPanel();
        central.setBackground(new Color(119, 135, 136));
          central.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1,Color.GRAY));
         
         
          JPanel h = new JPanel();
          central.add(jTabbedOriginal,"grow");
          jTabbedOriginal.addTab("Onglet 1", h);
         jTabbedOriginal.addTab("Onglet 2",new JPanel());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedOriginal = new javax.swing.JTabbedPane();

        jTabbedOriginal.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedOriginal.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedOriginal;
    // End of variables declaration//GEN-END:variables
}
